/* !! DONT PUT HEADER FILE PROTECTIONS IN THIS FILE !! */

#include  "button_manager_api.h"
#include  "src/button_manager.h"

#ifndef BUTTON_MANAGER_CLIENT_DEV
	#error "BUTTON_MANAGER_CLIENT_DEV should be defined"
#endif
#define POINTER_TO_BUTTON_MANAGER_CLIENT_DEV     \
		P_TO_STATIC_DEVICE_INST(BUTTON_MANAGER_CLIENT_DEV)


EXTERN_DECLARATION_TO_STATIC_DEVICE_INST(BUTTON_MANAGER_CLIENT_DEV);
SET_STATIC_DEV_CONFIG(button_manager) =
{
	POINTER_TO_BUTTON_MANAGER_CLIENT_DEV,
	NULL,
	NULL,
	0,
	0
};

#include "add_static_dev.h"

#undef  BUTTON_MANAGER_CLIENT_DEV
#undef  POINTER_TO_BUTTON_MANAGER_CLIENT_DEV
