/* !! DONT PUT HEADER FILE PROTECTIONS IN THIS FILE !! */

#include  "dma_i9xxxx_api.h"
#include  "src/dma_i9xxxx.h"


#if defined(CONFIG_I94XXX)
	#define I9XXXX_TEST_IF_PERIFERAL(type) \
		((type == DMA_I94XXX_API_TYPE_SPI1_RX) || \
		(type == DMA_I94XXX_API_TYPE_SPI1_TX) || \
		(type == DMA_I94XXX_API_TYPE_SPI2_RX) || \
		(type == DMA_I94XXX_API_TYPE_SPI2_TX) || \
		(type == DMA_I94XXX_API_TYPE_I2S_RX) || \
		(type == DMA_I94XXX_API_TYPE_I2S_TX) || \
		(type == DMA_I94XXX_API_TYPE_DPWM) || \
		(type == DMA_I94XXX_API_TYPE_DMIC))
	#define I9XXXX_TEST_IF_TX_PERIFERAL(type) \
		((type == DMA_I94XXX_API_TYPE_SPI1_TX) || \
		(type == DMA_I94XXX_API_TYPE_SPI2_TX) || \
		(type == DMA_I94XXX_API_TYPE_I2S_TX) || \
		(type == DMA_I94XXX_API_TYPE_DPWM))
#elif defined(CONFIG_I96XXX_M0)
	#define I9XXXX_TEST_IF_PERIFERAL(type) \
		((type == DMA_I96XXX_API_TYPE_SPI2_RX) || \
		(type == DMA_I96XXX_API_TYPE_SPI2_TX) || \
		(type == DMA_I96XXX_API_TYPE_I2S0_RX) || \
		(type == DMA_I96XXX_API_TYPE_I2S0_TX) || \
		(type == DMA_I96XXX_API_TYPE_I2S1_RX) || \
		(type == DMA_I96XXX_API_TYPE_I2S1_TX))
	#define I9XXXX_TEST_IF_TX_PERIFERAL(type) \
		((type == DMA_I96XXX_API_TYPE_SPI2_TX) || \
		(type == DMA_I96XXX_API_TYPE_I2S0_TX) || \
		(type == DMA_I96XXX_API_TYPE_I2S1_TX))
#endif


#ifndef DMA_I9XXXX_DT_CALLBACK_PDEV
	#define _DMA_I9XXXX_CALLBACK_PDEV   NULL
#else
	EXTERN_DECLARATION_TO_STATIC_DEVICE_INST(DMA_I9XXXX_DT_CALLBACK_PDEV);
	#define _DMA_I9XXXX_CALLBACK_PDEV  \
		P_TO_STATIC_DEVICE_INST(DMA_I9XXXX_DT_CALLBACK_PDEV)
#endif


#ifndef DMA_I9XXXX_DT_CHANNEL_NUM
	#error "DMA_I9XXXX_DT_CHANNEL_NUM should be defined"
#endif


#ifndef DMA_I9XXXX_DT_PERIPHERAL_TYPE
	#error "DMA_I9XXXX_DT_PERIPHERAL_TYPE should be defined"
#endif

#if I9XXXX_TEST_IF_PERIFERAL(DMA_I9XXXX_DT_PERIPHERAL_TYPE)

	#ifndef DMA_I9XXXX_DT_PERIPHERAL_DEV
		#error "DMA_I9XXXX_DT_PERIPHERAL_DEV should be defined"
	#else
		EXTERN_DECLARATION_TO_STATIC_DEVICE_INST(DMA_I9XXXX_DT_PERIPHERAL_DEV);
		#define _DMA_I9XXXX_PERIPHERAL_PDEV     \
				P_TO_STATIC_DEVICE_INST(DMA_I9XXXX_DT_PERIPHERAL_DEV)
	#endif

	#ifdef DMA_I9XXXX_DT_TRANSFER_WORD_SIZE
		#error "DMA_I9XXXX_DT_TRANSFER_WORD_SIZE cannot be defined for these peripherals"
	#endif
	#define DMA_I9XXXX_DT_TRANSFER_WORD_SIZE  DMA_I9XXXX_API_TRANSFER_WORD_32BIT

#else
	#ifndef DMA_I9XXXX_DT_TRANSFER_WORD_SIZE
		#error "DMA_I9XXXX_DT_TRANSFER_WORD_SIZE should be defined"
	#endif

	#define _DMA_I9XXXX_PERIPHERAL_PDEV   NULL
#endif

#if I9XXXX_TEST_IF_TX_PERIFERAL(DMA_I9XXXX_DT_PERIPHERAL_TYPE)
	#ifndef DMA_I9XXXX_DT_NUM_OF_PREFILLED_BUFFERS_BEFORE_TX_START
		#error "DMA_I9XXXX_DT_NUM_OF_PREFILLED_BUFFERS_BEFORE_TX_START should be defined"
	#endif
#else
	#undef DMA_I9XXXX_DT_NUM_OF_PREFILLED_BUFFERS_BEFORE_TX_START
	#define DMA_I9XXXX_DT_NUM_OF_PREFILLED_BUFFERS_BEFORE_TX_START  0
#endif

#ifndef DMA_I9XXXX_DT_BUFFER_SIZE
	#error "DMA_I9XXXX_DT_CHANNEL_NUM should be defined"
#endif

#ifndef DMA_I9XXXX_DT_NUM_OF_BUFFERS
	#error "DMA_I9XXXX_DT_NUM_OF_BUFFERS should be defined"
#endif



SET_STATIC_DEV_CONFIG(dma_i9xxxx) =
{
	_DMA_I9XXXX_CALLBACK_PDEV,
	_DMA_I9XXXX_PERIPHERAL_PDEV,
	DMA_I9XXXX_DT_CHANNEL_NUM,
	DMA_I9XXXX_DT_PERIPHERAL_TYPE,
	DMA_I9XXXX_DT_NUM_OF_BUFFERS,
	DMA_I9XXXX_DT_NUM_OF_PREFILLED_BUFFERS_BEFORE_TX_START,
	DMA_I9XXXX_DT_TRANSFER_WORD_SIZE,
	DMA_I9XXXX_DT_BUFFER_SIZE
};

#include "add_static_dev.h"

/*
 *  device specific defines should be undefined
 *  after calling #include "add_static_dev.h"
 */
#undef I9XXXX_TEST_IF_PERIFERAL
#undef I9XXXX_TEST_IF_TX_PERIFERAL
#undef DMA_I9XXXX_DT_CALLBACK_PDEV
#undef _DMA_I9XXXX_CALLBACK_PDEV
#undef DMA_I9XXXX_DT_PERIPHERAL_PDEV
#undef _DMA_I9XXXX_PERIPHERAL_PDEV
#undef DMA_I9XXXX_DT_CHANNEL_NUM
#undef DMA_I9XXXX_DT_PERIPHERAL_TYPE
#undef DMA_I9XXXX_DT_BUFFER_SIZE
#undef DMA_I9XXXX_DT_TRANSFER_WORD_SIZE
#undef DMA_I9XXXX_DT_PERIPHERAL_DEV
#undef _DMA_I9XXXX_PERIPHERAL_PDEV
#undef DMA_I9XXXX_DT_NUM_OF_BUFFERS
#undef DMA_I9XXXX_DT_NUM_OF_PREFILLED_BUFFERS_BEFORE_TX_START
