/*
 *  config.h
 *
 */

#ifndef _CONFIG_H
#define _CONFIG_H

#define HAVE_ISINF	1
#define HAVE_ISNAN	1
#define HAVE_CBRT	1
#define HAVE_CBRTF	1
#define HAVE_RINT	1
#define HAVE_LRINT	1
#define HAVE_LRINTF	1
#define HAVE_ROUND	1
#define HAVE_ROUNDF	1
#define HAVE_TRUNC	1
#define HAVE_TRUNCF	1
#define HAVE_LOCALTIME_R	1
#define HAVE_GMTIME_R	1
#define HAVE_MMX2	0
#define HAVE_MMXEXT	0


#define HAVE_PRAGMA_DEPRECATED 1




#define CONFIG_ACROSSFADE_FILTER		0
#define CONFIG_ADELAY_FILTER			0
#define CONFIG_AECHO_FILTER				0
#define CONFIG_AEVAL_FILTER				0
#define CONFIG_AFADE_FILTER				0
#define CONFIG_AFORMAT_FILTER			0
#define CONFIG_AINTERLEAVE_FILTER		0
#define CONFIG_ALLPASS_FILTER			1
#define CONFIG_AMERGE_FILTER			0
#define CONFIG_AMIX_FILTER				0
#define CONFIG_ANULL_FILTER				0
#define CONFIG_APAD_FILTER				0
#define CONFIG_APERMS_FILTER			0
#define CONFIG_APHASER_FILTER			0
#define CONFIG_ARESAMPLE_FILTER			0
#define CONFIG_AREVERSE_FILTER			0
#define CONFIG_ASELECT_FILTER			0
#define CONFIG_ASENDCMD_FILTER			0
#define CONFIG_ASETNSAMPLES_FILTER		0
#define CONFIG_ASETPTS_FILTER			0
#define CONFIG_ASETRATE_FILTER			0
#define CONFIG_ASETTB_FILTER			0
#define CONFIG_ASHOWINFO_FILTER			0
#define CONFIG_ASPLIT_FILTER			0
#define CONFIG_ASTATS_FILTER			0
#define CONFIG_ASTREAMSYNC_FILTER		0
#define CONFIG_ASYNCTS_FILTER			0
#define CONFIG_ATEMPO_FILTER			0
#define CONFIG_ATRIM_FILTER				0
#define CONFIG_AZMQ_FILTER				0
#define CONFIG_BANDPASS_FILTER			1
#define CONFIG_BANDREJECT_FILTER		1
#define CONFIG_BASS_FILTER				1
#define CONFIG_BIQUAD_FILTER			1
#define CONFIG_BS2B_FILTER				0
#define CONFIG_CHANNELMAP_FILTER		0
#define CONFIG_CHANNELSPLIT_FILTER		0
#define CONFIG_CHORUS_FILTER			0
#define CONFIG_COMPAND_FILTER			0
#define CONFIG_DCSHIFT_FILTER			0
#define CONFIG_DYNAUDNORM_FILTER		0
#define CONFIG_EARWAX_FILTER			0
#define CONFIG_EBUR128_FILTER			0
#define CONFIG_EQUALIZER_FILTER			1
#define CONFIG_FLANGER_FILTER			0
#define CONFIG_HIGHPASS_FILTER			1
#define CONFIG_JOIN_FILTER				0
#define CONFIG_LADSPA_FILTER			0
#define CONFIG_LOWPASS_FILTER			1
#define CONFIG_PAN_FILTER				0
#define CONFIG_REPLAYGAIN_FILTER		0
#define CONFIG_RESAMPLE_FILTER			0
#define CONFIG_SIDECHAINCOMPRESS_FILTER	0
#define CONFIG_SILENCEDETECT_FILTER		0
#define CONFIG_SILENCEREMOVE_FILTER		0
#define CONFIG_TREBLE_FILTER			1
#define CONFIG_VOLUME_FILTER			0
#define CONFIG_VOLUMEDETECT_FILTER		0

#define CONFIG_AEVALSRC_FILTER			0
#define CONFIG_ANULLSRC_FILTER			0
#define CONFIG_FLITE_FILTER				0
#define CONFIG_SINE_FILTER				0

#define CONFIG_ANULLSINK_FILTER			0

#define CONFIG_ALPHAEXTRACT_FILTER		0
#define CONFIG_ALPHAMERGE_FILTER		0
#define CONFIG_ATADENOISE_FILTER		0
#define CONFIG_ASS_FILTER				0
#define CONFIG_BBOX_FILTER				0
#define CONFIG_BLACKDETECT_FILTER		0
#define CONFIG_BLACKFRAME_FILTER		0
#define CONFIG_BLEND_FILTER				0
#define CONFIG_BOXBLUR_FILTER			0
#define CONFIG_CODECVIEW_FILTER			0
#define CONFIG_COLORBALANCE_FILTER		0
#define CONFIG_COLORCHANNELMIXER_FILTER	0
#define CONFIG_COLORKEY_FILTER			0
#define CONFIG_COLORLEVELS_FILTER		0
#define CONFIG_COLORMATRIX_FILTER		0
#define CONFIG_COPY_FILTER				0
#define CONFIG_COVER_RECT_FILTER		0
#define CONFIG_CROP_FILTER				0
#define CONFIG_CROPDETECT_FILTER		0
#define CONFIG_CURVES_FILTER			0
#define CONFIG_DCTDNOIZ_FILTER			0
#define CONFIG_DEBAND_FILTER			0
#define CONFIG_DECIMATE_FILTER			0
#define CONFIG_DEFLATE_FILTER			0
#define CONFIG_DEJUDDER_FILTER			0
#define CONFIG_DELOGO_FILTER			0
#define CONFIG_DESHAKE_FILTER			0
#define CONFIG_DETELECINE_FILTER		0
#define CONFIG_DILATION_FILTER			0
#define CONFIG_DRAWBOX_FILTER			0
#define CONFIG_DRAWGRAPH_FILTER			0
#define CONFIG_DRAWGRID_FILTER			0
#define CONFIG_DRAWTEXT_FILTER			0
#define CONFIG_EDGEDETECT_FILTER		0
#define CONFIG_ELBG_FILTER				0
#define CONFIG_EQ_FILTER				0
#define CONFIG_EROSION_FILTER			0
#define CONFIG_EXTRACTPLANES_FILTER		0
#define CONFIG_FADE_FILTER				0
#define CONFIG_FFTFILT_FILTER			0
#define CONFIG_FIELD_FILTER				0
#define CONFIG_FIELDMATCH_FILTER		0
#define CONFIG_FIELDORDER_FILTER		0
#define CONFIG_FIND_RECT_FILTER			0
#define CONFIG_FORMAT_FILTER			0
#define CONFIG_FPS_FILTER				0
#define CONFIG_FRAMEPACK_FILTER			0
#define CONFIG_FRAMESTEP_FILTER			0
#define CONFIG_FREI0R_FILTER			0
#define CONFIG_FSPP_FILTER				0
#define CONFIG_GEQ_FILTER				0
#define CONFIG_GRADFUN_FILTER			0
#define CONFIG_HALDCLUT_FILTER			0
#define CONFIG_HFLIP_FILTER				0
#define CONFIG_HISTEQ_FILTER			0
#define CONFIG_HISTOGRAM_FILTER			0
#define CONFIG_HQDN3D_FILTER			0
#define CONFIG_HQX_FILTER				0
#define CONFIG_HUE_FILTER				0
#define CONFIG_IDET_FILTER				0
#define CONFIG_IL_FILTER				0
#define CONFIG_INFLATE_FILTER			0
#define CONFIG_INTERLACE_FILTER			0
#define CONFIG_INTERLEAVE_FILTER		0
#define CONFIG_KERNDEINT_FILTER			0
#define CONFIG_LENSCORRECTION_FILTER	0
#define CONFIG_LUT3D_FILTER				0
#define CONFIG_LUT_FILTER				0
#define CONFIG_LUTRGB_FILTER			0
#define CONFIG_LUTYUV_FILTER			0
#define CONFIG_MCDEINT_FILTER			0
#define CONFIG_MERGEPLANES_FILTER		0
#define CONFIG_MPDECIMATE_FILTER		0
#define CONFIG_NEGATE_FILTER			0
#define CONFIG_NOFORMAT_FILTER			0
#define CONFIG_NOISE_FILTER				0
#define CONFIG_NULL_FILTER				0
#define CONFIG_OCV_FILTER				0
#define CONFIG_OVERLAY_FILTER			0
#define CONFIG_OWDENOISE_FILTER			0
#define CONFIG_PAD_FILTER				0
#define CONFIG_PALETTEGEN_FILTER		0
#define CONFIG_PALETTEUSE_FILTER		0
#define CONFIG_PERMS_FILTER				0
#define CONFIG_PERSPECTIVE_FILTER		0
#define CONFIG_PHASE_FILTER				0
#define CONFIG_PIXDESCTEST_FILTER		0
#define CONFIG_PP_FILTER				0
#define CONFIG_PP7_FILTER				0
#define CONFIG_PSNR_FILTER				0
#define CONFIG_PULLUP_FILTER			0
#define CONFIG_QP_FILTER				0
#define CONFIG_RANDOM_FILTER			0
#define CONFIG_REMOVEGRAIN_FILTER		0
#define CONFIG_REMOVELOGO_FILTER		0
#define CONFIG_REPEATFIELDS_FILTER		0
#define CONFIG_REVERSE_FILTER			0
#define CONFIG_ROTATE_FILTER			0
#define CONFIG_SAB_FILTER				0
#define CONFIG_SCALE_FILTER				0
#define CONFIG_SELECT_FILTER			0
#define CONFIG_SENDCMD_FILTER			0
#define CONFIG_SEPARATEFIELDS_FILTER	0
#define CONFIG_SETDAR_FILTER			0
#define CONFIG_SETFIELD_FILTER			0
#define CONFIG_SETPTS_FILTER			0
#define CONFIG_SETSAR_FILTER			0
#define CONFIG_SETTB_FILTER				0
#define CONFIG_SHOWINFO_FILTER			0
#define CONFIG_SHOWPALETTE_FILTER		0
#define CONFIG_SHUFFLEPLANES_FILTER		0
#define CONFIG_SIGNALSTATS_FILTER		0
#define CONFIG_SMARTBLUR_FILTER			0
#define CONFIG_SPLIT_FILTER				0
#define CONFIG_SPP_FILTER				0
#define CONFIG_SSIM_FILTER				0
#define CONFIG_STEREO3D_FILTER			0
#define CONFIG_SUBTITLES_FILTER			0
#define CONFIG_SUPER2XSAI_FILTER		0
#define CONFIG_SWAPUV_FILTER			0
#define CONFIG_TBLEND_FILTER			0
#define CONFIG_TELECINE_FILTER			0
#define CONFIG_THUMBNAIL_FILTER			0
#define CONFIG_TILE_FILTER				0
#define CONFIG_TINTERLACE_FILTER		0
#define CONFIG_TRANSPOSE_FILTER			0
#define CONFIG_TRIM_FILTER				0
#define CONFIG_UNSHARP_FILTER			0
#define CONFIG_USPP_FILTER				0
#define CONFIG_VFLIP_FILTER				0
#define CONFIG_VIDSTABDETECT_FILTER		0
#define CONFIG_VIDSTABTRANSFORM_FILTER	0
#define CONFIG_VIGNETTE_FILTER			0
#define CONFIG_W3FDIF_FILTER			0
#define CONFIG_XBR_FILTER				0
#define CONFIG_YADIF_FILTER				0
#define CONFIG_ZMQ_FILTER				0
#define CONFIG_ZOOMPAN_FILTER			0

#define CONFIG_ALLYUV_FILTER			0
#define CONFIG_CELLAUTO_FILTER			0
#define CONFIG_COLOR_FILTER				0
#define CONFIG_FREI0R_FILTER			0
#define CONFIG_HALDCLUTSRC_FILTER		0
#define CONFIG_LIFE_FILTER				0
#define CONFIG_MANDELBROT_FILTER		0
#define CONFIG_MPTESTSRC_FILTER			0
#define CONFIG_NULLSRC_FILTER			0
#define CONFIG_RGBTESTSRC_FILTER		0
#define CONFIG_SMPTEBARS_FILTER			0
#define CONFIG_SMPTEHDBARS_FILTER		0
#define CONFIG_TESTSRC_FILTER			0

#define CONFIG_NULLSINK_FILTER			0


#define CONFIG_ADRAWGRAPH_FILTER		0
#define CONFIG_AVECTORSCOPE_FILTER		0
#define CONFIG_CONCAT_FILTER			0
#define CONFIG_SHOWCQT_FILTER			0
#define CONFIG_SHOWSPECTRUM_FILTER		0
#define CONFIG_SHOWVOLUME_FILTER		0
#define CONFIG_SHOWWAVES_FILTER			0
#define CONFIG_SHOWWAVESPIC_FILTER		0


#define CONFIG_AMOVIE_FILTER			0
#define CONFIG_MOVIE_FILTER				0


#define CONFIG_MEMORY_POISONING 0
//#define FF_MEMORY_POISON 0

#define CONFIG_FTRAPV	0



#define HAVE_AV_CONFIG_H 1


#endif /* AVUTIL_AVCONFIG_H */
