
ifdef CONFIG_NUC505
    INCLUDE_THIS_COMPONENT := $(CONFIG_INCLUDE_INTERNAL_UART)
    DYNAMIC_COMPONENT := $(CONFIG_INCLUDE_INTERNAL_UART)
endif

INCLUDE_DIR = $(EXTERNAL_SOURCE_ROOT_DIR)/BSP_NUC505_v3.00.003/Library/Device/Nuvoton/NUC505Series/Include

#INCLUDE_DIR = $(DRIVERS_ROOT_DIR)/Obtainable/ST/nuc505s-periphs/inc

#DEFINES = 

#CFLAGS = 

#ASMFLAGS =  



SRC = uart_nuc505.c

VPATH = src

SRC += uart.c
SRC += sys.c

VPATH += | $(EXTERNAL_SOURCE_ROOT_DIR)/BSP_NUC505_v3.00.003/Library/StdDriver/src

include $(COMMON_CC)
