/* !! DONT PUT HEADER FILE PROTECTIONS IN THIS FILE !! */

#include "src/uart_i9xxxx.h"
#include "uart_i9xxxx_api.h"

#ifdef CONFIG_I94XXX
	#include "I94100.h"
	#undef UART_I9XXXX_DT_BASE_ADDRESS
	#define UART_I9XXXX_DT_BASE_ADDRESS (size_t)UART0_BASE
#else
	#ifndef UART_I9XXXX_DT_BASE_ADDRESS
		#error "UART_I9XXXX_DT_BASE_ADDRESS should be defined"
	#endif
#endif

#ifdef UART_I9XXXX_DT_TX_CALLBACK_PDEV
	EXTERN_DECLARATION_TO_STATIC_DEVICE_INST(UART_I9XXXX_DT_TX_CALLBACK_PDEV);
	#define _POINTER_TO_TX_CALLBACK_PDEV        \
			P_TO_STATIC_DEVICE_INST(UART_I9XXXX_DT_TX_CALLBACK_PDEV)
#else
	#warning "UART_I9XXXX_DT_TX_CALLBACK_PDEV not defined in device tree"
	#define POINTER_TO_TX_CALLBACK_PDEV        NULL
#endif

#ifdef UART_I9XXXX_DT_RX_CALLBACK_PDEV
	EXTERN_DECLARATION_TO_STATIC_DEVICE_INST(UART_I9XXXX_DT_RX_CALLBACK_PDEV);
	#define _POINTER_TO_RX_CALLBACK_PDEV        \
		P_TO_STATIC_DEVICE_INST(UART_I9XXXX_DT_RX_CALLBACK_PDEV)
#else
	#warning "UART_I9XXXX_DT_RX_CALLBACK_PDEV not defined in device tree"
	#define POINTER_TO_RX_CALLBACK_PDEV        NULL
#endif

#ifndef UART_I9XXXX_DT_BAUD_RATE
	#error "UART_I9XXXX_DT_BAUD_RATE should be defined"
#endif

#ifndef UART_I9XXXX_DT_SRC_CLOCK_PDEV
	#error "UART_I9XXXX_DT_SRC_CLOCK_PDEV should be defined"
#endif
EXTERN_DECLARATION_TO_STATIC_DEVICE_INST(UART_I9XXXX_DT_SRC_CLOCK_PDEV) ;
#define _POINTER_TO_SRC_CLOCK_PDEV     \
		P_TO_STATIC_DEVICE_INST(UART_I9XXXX_DT_SRC_CLOCK_PDEV)

#ifndef UART_I9XXXX_DT_TX_PIN
	#error "UART_I9XXXX_DT_TX_PIN should be defined"
#endif

#ifndef UART_I9XXXX_DT_RX_PIN
	#error "UART_I9XXXX_DT_RX_PIN should be defined"
#endif

SET_STATIC_DEV_CONFIG(uart_i9xxxx) =
{
	_POINTER_TO_TX_CALLBACK_PDEV,
	_POINTER_TO_RX_CALLBACK_PDEV,
	_POINTER_TO_SRC_CLOCK_PDEV,
	UART_I9XXXX_DT_BASE_ADDRESS,
	UART_I9XXXX_DT_BAUD_RATE,
	UART_I9XXXX_DT_TX_PIN,
	UART_I9XXXX_DT_RX_PIN,
};


#include "add_static_dev.h"

/*
 *  device specific defines should be undefined
 *  after calling #include "add_static_dev.h"
 */
#undef UART_I96XXX_API_BASE_ADDRESS_UART0
#undef _POINTER_TO_SRC_CLOCK_PDEV
#undef _POINTER_TO_TX_CALLBACK_PDEV
#undef _POINTER_TO_RX_CALLBACK_PDEV
#undef UART_I9XXXX_DT_UART_NUMBER
#undef UART_I9XXXX_DT_CALLBACK_PDEV
#undef UART_I9XXXX_DT_BAUD_RATE
#undef UART_I9XXXX_DT_SRC_CLOCK_PDEV
#undef UART_I9XXXX_DT_TX_PIN
#undef UART_I9XXXX_DT_RX_PIN
