ifdef CONFIG_NUC505
    INCLUDE_THIS_COMPONENT := $(CONFIG_INCLUDE_INTERNAL_CLOCK_CONTROL)
endif


#INCLUDE_DIR =$(EXTERNAL_SOURCE_ROOT_DIR)/BSP_NUC505_v3.00.003/Library/StdDriver/inc

#DEFINES = 

#CFLAGS = 

#ASMFLAGS =  



SRC = clocks_control_nuc505.c
VPATH = src

SRC += clk.c
SRC += spim.c
VPATH +=  | $(EXTERNAL_SOURCE_ROOT_DIR)/BSP_NUC505_v3.00.003/Library/StdDriver/src

include $(COMMON_CC)
