
INCLUDE_THIS_COMPONENT := $(CONFIG_INCLUDE_COMMON_DSP) $(CONFIG_AUTO_INCLUDE_COMMON_DSP)

#INCLUDE_DIR =

#DEFINES =

#CFLAGS =

#ASMFLAGS =




SRC = math_functions.cpp
VPATH = src



ifdef CONFIG_COMMON_DSP_IS_SPEED_CRITICAL
    _COMMON_DSP_IS_SPEED_CRITICAL:=YES
endif
ifdef CONFIG_AUTO_COMMON_DSP_IS_SPEED_CRITICAL
    _COMMON_DSP_IS_SPEED_CRITICAL:=YES
endif

ifdef _COMMON_DSP_IS_SPEED_CRITICAL
    SPEED_CRITICAL_FILES += math_functions.cpp
endif


include $(COMMON_CC)
