/* !! DONT PUT HEADER FILE PROTECTIONS IN THIS FILE !! */

#include  "shell_frontend_api.h"
#include  "src/shell_frontend.h"


#ifndef SHELL_FRONTEND_DT_TX_SERVER_PDEV
	#error "SHELL_FRONTEND_DT_TX_SERVER_PDEV should be defined"
#endif

#ifndef SHELL_FRONTEND_DT_RX_SERVER_PDEV
	#error "SHELL_FRONTEND_DT_RX_SERVER_PDEV should be defined"
#endif

#ifndef SHELL_FRONTEND_DT_SHELL_BACKEND_PDEV
	#define _SHELL_BACKEND_PDEV  NULL
#else
	EXTERN_DECLARATION_TO_STATIC_DEVICE_INST(
					SHELL_FRONTEND_DT_SHELL_BACKEND_PDEV) ;
	#define _SHELL_BACKEND_PDEV  \
		P_TO_STATIC_DEVICE_INST(SHELL_FRONTEND_DT_SHELL_BACKEND_PDEV)
#endif


#ifndef SHELL_FRONTEND_DT_CMD_SAVE_PDEV
	#define _CMD_SAVE_PDEV	NULL
#else
	EXTERN_DECLARATION_TO_STATIC_DEVICE_INST(SHELL_FRONTEND_DT_CMD_SAVE_PDEV);
	#define _CMD_SAVE_PDEV  \
			P_TO_STATIC_DEVICE_INST(SHELL_FRONTEND_DT_CMD_SAVE_PDEV)
#endif

EXTERN_DECLARATION_TO_STATIC_DEVICE_INST(SHELL_FRONTEND_DT_TX_SERVER_PDEV);
EXTERN_DECLARATION_TO_STATIC_DEVICE_INST(SHELL_FRONTEND_DT_RX_SERVER_PDEV);
SET_STATIC_DEV_CONFIG(shell_frontend) =
{
	P_TO_STATIC_DEVICE_INST(SHELL_FRONTEND_DT_TX_SERVER_PDEV),
	P_TO_STATIC_DEVICE_INST(SHELL_FRONTEND_DT_RX_SERVER_PDEV),
	_SHELL_BACKEND_PDEV,
	_CMD_SAVE_PDEV
};

#include "add_static_dev.h"

/*
 *  device specific defines should be undefined
 *  after calling #include "add_static_dev.h"
 */
#undef SHELL_FRONTEND_DT_TX_SERVER_PDEV
#undef SHELL_FRONTEND_DT_RX_SERVER_PDEV
#undef SHELL_FRONTEND_DT_SHELL_BACKEND_PDEV
#undef SHELL_FRONTEND_DT_CMD_SAVE_PDEV
#undef _CALLBACK_PDEV
#undef _CMD_SAVE_PDEV
