
HASH=\#
COMPONENT_PATH := $(call calc_parent_dir,$(COMPONENT_CONFIG_FILE))
COMPONENT_NAME := $(notdir $(COMPONENT_PATH))
include $(COMPONENT_CONFIG_FILE)
ifeq ($(sort $(INCLUDE_THIS_COMPONENT)),y)
  AUTO_GLOBAL_INCLUDE_DIR := $(AUTO_GLOBAL_INCLUDE_DIR) $(COMPONENT_PATH)
  SUBDIRS := $(SUBDIRS) $(COMPONENT_PATH)
endif 

ifeq ($(filter y,$(INCLUDE_THIS_FOR_H_FILES_PATH)),y) 
    AUTO_GLOBAL_INCLUDE_DIR := $(AUTO_GLOBAL_INCLUDE_DIR) $(COMPONENT_PATH)
endif

INCLUDE_THIS_COMPONENT := NO
INCLUDE_THIS_FOR_H_FILES_PATH := NO
