
ifeq ($(findstring YES,$(_INCLUDE_DSP_MANAGMENT)),YES) 	 
	INCLUDE_THIS_FOR_H_FILES_PATH := YES
    GLOBAL_INCLUDE_DIR := $(call ADD_TO_GLOBAL_INCLUDE_PATH , $(EXTERNAL_SOURCE_ROOT_DIR)/ffmpeg )
    GLOBAL_INCLUDE_DIR := $(call ADD_TO_GLOBAL_INCLUDE_PATH , $(EXTERNAL_SOURCE_ROOT_DIR)/ffmpeg/libavfilter )
endif  

