
ifdef CONFIG_NUC505
    INCLUDE_THIS_COMPONENT := $(CONFIG_INCLUDE_INTERNAL_GPIO)
    DYNAMIC_COMPONENT := $(CONFIG_INCLUDE_INTERNAL_GPIO)
endif


GLOBAL_INCLUDE_DIR += $(EXTERNAL_SOURCE_ROOT_DIR)/BSP_NUC505_v3.00.003/Library/StdDriver/inc

#DEFINES = 

#CFLAGS = 

#ASMFLAGS =  



SRC = gpio_nuc505.c 
VPATH = src

SRC += gpio.c
VPATH += | $(EXTERNAL_SOURCE_ROOT_DIR)/BSP_NUC505_v3.00.003/Library/StdDriver/src

include $(COMMON_CC)
