/* !! DONT PUT HEADER FILE PROTECTIONS IN THIS FILE !! */

#include  "usb_hid_class_api.h"
#include  "src/usb_hid_class.h"


#ifndef USB_HID_CLASS_DT_USB_PDEV
	#error "USB_HID_CLASS_DT_USB_PDEV should be defined"
#endif
EXTERN_DECLARATION_TO_STATIC_DEVICE_INST(USB_HID_CLASS_DT_USB_PDEV);
#define _POINTER_TO_USB_PDEV  P_TO_STATIC_DEVICE_INST(USB_HID_CLASS_DT_USB_PDEV)

#ifndef USB_HID_CLASS_DT_USB_DESCRIPTOR_PDEV
	#error "USB_HID_CLASS_DT_USB_DESCRIPTOR_PDEV should be defined"
#endif
EXTERN_DECLARATION_TO_STATIC_DEVICE_INST(USB_HID_CLASS_DT_USB_DESCRIPTOR_PDEV);
#define _POINTER_TO_USB_DESCRIPTOR_PDEV     \
		P_TO_STATIC_DEVICE_INST(USB_HID_CLASS_DT_USB_DESCRIPTOR_PDEV)

#ifndef USB_HID_CLASS_DT_MAX_DATA_HOST_IN_PCKT_SIZE
	#error "USB_HID_CLASS_DT_MAX_DATA_HOST_IN_PCKT_SIZE should be defined"
#endif

#ifndef USB_HID_CLASS_DT_MAX_DATA_HOST_OUT_PCKT_SIZE
	#error "USB_HID_CLASS_DT_MAX_DATA_HOST_OUT_PCKT_SIZE should be defined"
#endif

SET_STATIC_DEV_CONFIG(usb_hid_class) =
{
	_POINTER_TO_USB_PDEV,
	_POINTER_TO_USB_DESCRIPTOR_PDEV,
	USB_HID_CLASS_DT_MAX_DATA_HOST_IN_PCKT_SIZE,
	USB_HID_CLASS_DT_MAX_DATA_HOST_OUT_PCKT_SIZE
};


#include "add_static_dev.h"

/*
 *  device specific defines should be undefined
 *  after calling #include "add_static_dev.h"
 */
#undef _POINTER_TO_USB_PDEV
#undef USB_HID_CLASS_DT_USB_DESCRIPTOR_PDEV
#undef _POINTER_TO_USB_DESCRIPTOR_PDEV
#undef USB_HID_CLASS_DT_MAX_DATA_HOST_IN_PCKT_SIZE
#undef USB_HID_CLASS_DT_MAX_DATA_HOST_OUT_PCKT_SIZE
