/* !! DONT PUT HEADER FILE PROTECTIONS IN THIS FILE !! */

#include  "shell_presets_api.h"
#include  "src/shell_presets.h"

#ifndef SHELL_PRESETS_DT_STORAGE_PDEV
	#error "SHELL_PRESETS_DT_STORAGE_PDEV should be defined"
#endif

#ifndef SHELL_PRESETS_DT_MAX_PRESET_SIZE
	#error "SHELL_PRESETS_DT_MAX_PRESET_SIZE should be defined"
#endif


#ifndef SHELL_PRESETS_DT_MAX_NUM_OF_PRESETS
	#error "SHELL_PRESETS_DT_MAX_NUM_OF_PRESETS should be defined"
#endif

#ifndef SHELL_PRESETS_DT_START_ADDRESS_ON_STORAGE
	#error "SHELL_PRESETS_DT_START_ADDRESS_ON_STORAGE should be defined"
#endif


EXTERN_DECLARATION_TO_STATIC_DEVICE_INST(SHELL_PRESETS_DT_STORAGE_PDEV) ;
SET_STATIC_DEV_CONFIG(shell_presets) =
{
	P_TO_STATIC_DEVICE_INST(SHELL_PRESETS_DT_STORAGE_PDEV),
	SHELL_PRESETS_DT_START_ADDRESS_ON_STORAGE,
	SHELL_PRESETS_DT_MAX_PRESET_SIZE,
	SHELL_PRESETS_DT_MAX_NUM_OF_PRESETS
};



#include "add_static_dev.h"

/**
 *  device specific defines should be undefined
 *  after calling #include "add_static_dev.h"
 */
#undef SHELL_PRESETS_DT_STORAGE_PDEV
#undef SHELL_PRESETS_DT_MAX_PRESET_SIZE
#undef SHELL_PRESETS_DT_MAX_NUM_OF_PRESETS
#undef SHELL_PRESETS_DT_START_ADDRESS_ON_STORAGE
