
#ifndef _UART_STM32F10x_API_H_
#define _UART_STM32F10x_API_H_

#include "uart_api.h"



#define UART_STM32F10X_API_UART_NUM_STR "uart_num"
#define UART_STM32F10X_API_UART_DISABLE_STR "disable"


enum UART_STM32F10X_API_ioctl_e {
	IOCTL_UART_STM32F10X_SET_UART_NUM = IOCTL_LAST_COMMON_UART_IOCTL + 1,
	IOCTL_UART_STM32F10X_DISABLE
};


#endif
