
#ifndef _I2S_I94XXX_API_H_
#define _I2S_I94XXX_API_H_

#include "dev_management_api.h"
#include "i2s.h"

/*****************  defines  **************/

#define I2S_I94XXX_API_MASTER_MODE    I2S_MASTER
#define I2S_I94XXX_API_SLAVE_MODE     I2S_SLAVE

#define I2S_I94XXX_API_DI_PIN_B13    1
#define I2S_I94XXX_API_DI_PIN_D4     2

#define I2S_I94XXX_API_DO_PIN_B14    3
#define I2S_I94XXX_API_DO_PIN_D5     4

#define I2S_I94XXX_API_MCLK_PIN_B15    5
#define I2S_I94XXX_API_MCLK_PIN_D2     6
#define I2S_I94XXX_API_MCLK_PIN_NONE   7

#define I2S_I94XXX_API_LRCLK_PIN_D1    8
#define I2S_I94XXX_API_LRCLK_PIN_D3    9

#define I2S_I94XXX_API_BCLK_PIN_D0     10
#define I2S_I94XXX_API_BCLK_PIN_D6     11

#define I2S_I94XXX_FORMAT_I2S          I2S_FORMAT_I2S
#define I2S_I94XXX_FORMAT_MSB          I2S_FORMAT_MSB
#define I2S_I94XXX_FORMAT_LSB          I2S_FORMAT_LSB
#define I2S_I94XXX_FORMAT_PCM          I2S_FORMAT_PCM
#define I2S_I94XXX_FORMAT_PCMMSB       I2S_FORMAT_PCMMSB
#define I2S_I94XXX_FORMAT_PCMLSB       I2S_FORMAT_PCMLSB


#define I2S_I94XXX_API_AUDIO_FORMAT_STEREO     I2S_STEREO
#define I2S_I94XXX_API_AUDIO_FORMAT_MONO       I2S_MONO


/**********  define API  types ************/

typedef enum
{
	I2S_I94XXX_ENABLE_OUTPUT_IOCTL = IOCTL_LAST_COMMON_IOCTL + 1,
	I2S_I94XXX_STOP_IOCTL,
	I2S_I94XXX_GET_MEASURED_SAMPLE_RATE,
	I2S_I94XXX_SYNC_FS_TO_DPWM_FS_RATE
}I2S_I94XXX_API_ioctl_t;



/**********  define API  functions  ************/

#endif
