/* !! DONT PUT HEADER FILE PROTECTIONS IN THIS FILE !! */

#include  "dma_i94xxx_api.h"
#include  "src/dma_i94xxx.h"


#define	MODULE_NAME                         dma_i94xxx
#define	MODULE_IOCTL_FUNCTION               dma_i94xxx_ioctl
#define MODULE_CONFIG_DATA_STRUCT_TYPE      struct dma_i94xxx_cfg_t
#define MODULE_RUNTIME_DATA_STRUCT_TYPE     struct dma_i94xxx_runtime_t

#ifdef DT_DEV_MODULE

	#ifndef DMA_I94XXX_DT_CALLBACK_PDEV
		#define _DMA_I94XXX_CALLBACK_PDEV   NULL
	#else
		EXTERN_DECLARATION_TO_STATIC_DEVICE_INST(DMA_I94XXX_DT_CALLBACK_PDEV);
		#define _DMA_I94XXX_CALLBACK_PDEV  \
			P_TO_STATIC_DEVICE_INST(DMA_I94XXX_DT_CALLBACK_PDEV)
	#endif


	#ifndef DMA_I94XXX_DT_CHANNEL_NUM
		#error "DMA_I94XXX_DT_CHANNEL_NUM should be defined"
	#endif


	#ifndef DMA_I94XXX_DT_PERIPHERAL_TYPE
		#error "DMA_I94XXX_DT_PERIPHERAL_TYPE should be defined"
	#endif

	#if ( (DMA_I94XXX_DT_PERIPHERAL_TYPE == DMA_I94XXX_API_TYPE_I2S_TX) || \
			(DMA_I94XXX_DT_PERIPHERAL_TYPE == DMA_I94XXX_API_TYPE_I2S_RX) || \
			(DMA_I94XXX_DT_PERIPHERAL_TYPE == DMA_I94XXX_API_TYPE_DPWM) || \
			(DMA_I94XXX_DT_PERIPHERAL_TYPE == DMA_I94XXX_API_TYPE_SPI1_RX) || \
			(DMA_I94XXX_DT_PERIPHERAL_TYPE == DMA_I94XXX_API_TYPE_SPI1_TX) || \
			(DMA_I94XXX_DT_PERIPHERAL_TYPE == DMA_I94XXX_API_TYPE_SPI2_RX) || \
			(DMA_I94XXX_DT_PERIPHERAL_TYPE == DMA_I94XXX_API_TYPE_SPI2_TX) )


		#ifndef DMA_I94XXX_DT_PERIPHERAL_DEV
			#error "DMA_I94XXX_DT_PERIPHERAL_DEV should be defined"
		#else
			EXTERN_DECLARATION_TO_STATIC_DEVICE_INST(
										DMA_I94XXX_DT_PERIPHERAL_DEV);
			#define _DMA_I94XXX_PERIPHERAL_PDEV     \
					P_TO_STATIC_DEVICE_INST(DMA_I94XXX_DT_PERIPHERAL_DEV)
		#endif

		#ifdef DMA_I94XXX_DT_TRANSFER_WORD_SIZE
			#error "DMA_I94XXX_DT_TRANSFER_WORD_SIZE cannot be defined for these peripherals"
		#endif
		#define DMA_I94XXX_DT_TRANSFER_WORD_SIZE   \
											DMA_I94XXX_API_TRANSFER_WORD_32BIT
	#else
		#ifndef DMA_I94XXX_DT_TRANSFER_WORD_SIZE
			#error "DMA_I94XXX_DT_TRANSFER_WORD_SIZE should be defined"
		#endif

		#define _DMA_I94XXX_PERIPHERAL_PDEV   NULL
	#endif

	#ifndef DMA_I94XXX_DT_BUFFER_SIZE
		#error "DMA_I94XXX_DT_CHANNEL_NUM should be defined"
	#endif


	#define STATIC_DEV_DATA_STRUCT             \
		{                                      \
			_DMA_I94XXX_CALLBACK_PDEV ,        \
			_DMA_I94XXX_PERIPHERAL_PDEV,       \
			DMA_I94XXX_DT_CHANNEL_NUM,         \
			DMA_I94XXX_DT_PERIPHERAL_TYPE,     \
			DMA_I94XXX_DT_TRANSFER_WORD_SIZE,  \
			DMA_I94XXX_DT_BUFFER_SIZE          \
		}

#endif

#include "add_component.h"

/*
 *  device specific defines should be undefined
 *  after calling #include "add_component.h"
 */
#undef DMA_I94XXX_DT_CALLBACK_PDEV
#undef _DMA_I94XXX_CALLBACK_PDEV
#undef DMA_I94XXX_DT_PERIPHERAL_PDEV
#undef _DMA_I94XXX_PERIPHERAL_PDEV
#undef DMA_I94XXX_DT_CHANNEL_NUM
#undef DMA_I94XXX_DT_PERIPHERAL_TYPE
#undef DMA_I94XXX_DT_BUFFER_SIZE
#undef DMA_I94XXX_DT_TRANSFER_WORD_SIZE
#undef DMA_I94XXX_DT_PERIPHERAL_DEV
#undef _DMA_I94XXX_PERIPHERAL_PDEV
