
#ifndef _STM8_TIM1_API_H_
#define _STM8_TIM1_API_H_

#include "stm8s_tim1.h"

#define STM8_TIM1_COUNTER_MODE_UP		TIM1_COUNTERMODE_UP
#define STM8_TIM1_COUNTER_MODE_DOWN		TIM1_COUNTERMODE_DOWN

#endif
