CONFIG_PROJECT_NAME :=$(strip $(CONFIG_PROJECT_NAME))
CONFIG_NAME_SUFFIX_IN_BUNDLE :=$(strip $(CONFIG_NAME_SUFFIX_IN_BUNDLE))

ifeq (,$(CONFIG_NAME_SUFFIX_IN_BUNDLE))
    FULL_PROJECT_NAME :=$(CONFIG_PROJECT_NAME)
else
    FULL_PROJECT_NAME :=$(CONFIG_PROJECT_NAME)_$(CONFIG_NAME_SUFFIX_IN_BUNDLE)
endif

ifeq ($(FULL_PROJECT_NAME),$(FULL_CURR_PROJECT_NAME))
    $(info err: name is not unique)
    $(call exit,1)
endif
