
#ifndef _LM35_API_H_
#define _LM35_API_H_


#define LM35_API_SERVER_DEVICE_STR  			"server_device"

enum LM35_API_ioctl_e {
	IOCTL_LM35_SET_SERVER_DEVICE = IOCTL_LAST_COMMON_IOCTL + 1,
	IOCTL_LM35_GET_CURRENT_TEMPERATURE_mC,
};


#endif
