/* !! DONT PUT HEADER FILE PROTECTIONS IN THIS FILE !! */

#include  "I2S_onSPI_i94xxx_api.h"
#include "src/I2S_onSPI_i94xxx.h"


#ifndef I2S_onSPI_I94XXX_DT_MASTER_OR_SLAVE_MODE
	#error "I2S_onSPI_I94XXX_DT_MASTER_OR_SLAVE_MODE should be defined"
#endif

#if	(I2S_onSPI_I94XXX_DT_MASTER_OR_SLAVE_MODE == \
							I2S_onSPI_I94XXX_API_MASTER_MODE)
	#ifndef I2S_onSPI_I94XXX_DT_SAMPLE_RATE
		#error "I2S_onSPI_I94XXX_DT_SAMPLE_RATE should be defined"
	#endif
#endif

#ifndef I2S_onSPI_I94XXX_DT_NUM_OF_BYTES_IN_WORD
	#error "I2S_onSPI_I94XXX_DT_NUM_OF_BYTES_IN_WORD should be defined"
#else
	#if (I2S_onSPI_I94XXX_DT_NUM_OF_BYTES_IN_WORD == 1)
		#define _I2S_onSPI_I94XXX_DT_NUM_OF_BYTES_IN_WORD SPI_I2SDATABIT_8

	#elif (I2S_onSPI_I94XXX_DT_NUM_OF_BYTES_IN_WORD == 2)
		#define _I2S_onSPI_I94XXX_DT_NUM_OF_BYTES_IN_WORD SPI_I2SDATABIT_16

	#elif (I2S_onSPI_I94XXX_DT_NUM_OF_BYTES_IN_WORD == 3)
		#define _I2S_onSPI_I94XXX_DT_NUM_OF_BYTES_IN_WORD SPI_I2SDATABIT_24

	#elif (I2S_onSPI_I94XXX_DT_NUM_OF_BYTES_IN_WORD == 4)
		#define _I2S_onSPI_I94XXX_DT_NUM_OF_BYTES_IN_WORD SPI_I2SDATABIT_32

	#endif
#endif

#ifndef I2S_onSPI_I94XXX_DT_BASE_ADDRESS
	#error "I2S_onSPI_I94XXX_DT_BASE_ADDRESS should be defined"
#endif

#ifndef I2S_onSPI_I94XXX_DT_AUDIO_FORMAT
	#error "I2S_onSPI_I94XXX_DT_AUDIO_FORMAT should be defined"
#endif

#ifndef I2S_onSPI_I94XXX_DT_TXRX_FORMAT
	#error "I2S_onSPI_I94XXX_DT_TXRX_FORMAT should be defined"
#endif

#ifndef I2S_onSPI_I94XXX_DT_ENABLE_CHANNEL_REORDERING
	#define I2S_onSPI_I94XXX_DT_ENABLE_CHANNEL_REORDERING  0
#endif

#ifndef I2S_onSPI_I94XXX_DT_MCLK_FACTOR_BASED_ON_FSCLK
	#error "I2S_onSPI_I94XXX_DT_MCLK_FACTOR_BASED_ON_FSCLK should be defined"
#endif

#ifndef I2S_onSPI_I94XXX_DT_BCLK_PIN
	#error "I2S_onSPI_I94XXX_DT_BCLK_PIN should be defined"
#endif

#ifndef I2S_onSPI_I94XXX_DT_LRCLK_PIN
	#error "I2S_onSPI_I94XXX_DT_LRCLK_PIN should be defined"
#endif

#ifndef I2S_onSPI_I94XXX_DT_DI_PIN
	#error "I2S_onSPI_I94XXX_DT_DI_PIN should be defined"
#endif

#ifndef I2S_onSPI_I94XXX_DT_DO_PIN
	#error "I2S_onSPI_I94XXX_DT_DO_PIN should be defined"
#endif

#ifndef I2S_onSPI_I94XXX_DT_MCLK_PIN
	#warning "I2S_onSPI_I94XXX_DT_MCLK_PIN is not defined"
	#define I2S_onSPI_I94XXX_DT_MCLK_PIN    0xffffffff
#endif

#ifndef I2S_onSPI_I94XXX_DT_SRC_CLOCK_PDEV
	#error "I2S_onSPI_I94XXX_DT_SRC_CLOCK_PDEV should be defined"
#endif
EXTERN_DECLARATION_TO_STATIC_DEVICE_INST(I2S_onSPI_I94XXX_DT_SRC_CLOCK_PDEV);
#define POINTER_TO_SRC_CLOCK_PDEV  \
		P_TO_STATIC_DEVICE_INST(I2S_onSPI_I94XXX_DT_SRC_CLOCK_PDEV)


SET_STATIC_DEV_CONFIG(I2S_onSPI_i94xxx) =
{
	POINTER_TO_SRC_CLOCK_PDEV,
	I2S_onSPI_I94XXX_DT_BASE_ADDRESS,
	I2S_onSPI_I94XXX_DT_MASTER_OR_SLAVE_MODE,
	I2S_onSPI_I94XXX_DT_SAMPLE_RATE,
	_I2S_onSPI_I94XXX_DT_NUM_OF_BYTES_IN_WORD,
	I2S_onSPI_I94XXX_DT_AUDIO_FORMAT,
	I2S_onSPI_I94XXX_DT_TXRX_FORMAT,
	I2S_onSPI_I94XXX_DT_MCLK_FACTOR_BASED_ON_FSCLK,
	I2S_onSPI_I94XXX_DT_BCLK_PIN,
	I2S_onSPI_I94XXX_DT_LRCLK_PIN,
	I2S_onSPI_I94XXX_DT_DI_PIN,
	I2S_onSPI_I94XXX_DT_DO_PIN,
	I2S_onSPI_I94XXX_DT_MCLK_PIN,
	I2S_onSPI_I94XXX_DT_ENABLE_CHANNEL_REORDERING
};


#include "add_static_dev.h"

#undef POINTER_TO_SRC_CLOCK_PDEV
#if	(I2S_onSPI_I94XXX_DT_MASTER_OR_SLAVE_MODE == I2S_onSPI_I94XXX_API_MASTER_MODE)
    #undef I2S_onSPI_I94XXX_DT_SAMPLE_RATE
#endif
#undef I2S_onSPI_I94XXX_DT_MASTER_OR_SLAVE_MODE
#undef I2S_onSPI_I94XXX_DT_NUM_OF_BYTES_IN_WORD
#undef _I2S_onSPI_I94XXX_DT_NUM_OF_BYTES_IN_WORD
#undef I2S_onSPI_I94XXX_DT_BASE_ADDRESS
#undef I2S_onSPI_I94XXX_DT_AUDIO_FORMAT
#undef I2S_onSPI_I94XXX_DT_TXRX_FORMAT
#undef I2S_onSPI_I94XXX_DT_BCLK_PIN
#undef I2S_onSPI_I94XXX_DT_LRCLK_PIN
#undef I2S_onSPI_I94XXX_DT_DI_PIN
#undef I2S_onSPI_I94XXX_DT_DO_PIN
#undef I2S_onSPI_I94XXX_DT_MCLK_PIN
#undef I2S_onSPI_I94XXX_DT_ENABLE_CHANNEL_REORDERING
#undef I2S_onSPI_I94XXX_DT_MCLK_FACTOR_BASED_ON_FSCLK
