CONFIG_PROJECT_NAME :=$(strip $(CONFIG_PROJECT_NAME))
CONFIG_PROJECT_NAME_SUFFIX :=$(strip $(CONFIG_PROJECT_NAME_SUFFIX))

ifeq (,$(CONFIG_PROJECT_NAME_SUFFIX))
    FULL_PROJECT_NAME :=$(CONFIG_PROJECT_NAME)
else
    FULL_PROJECT_NAME :=$(CONFIG_PROJECT_NAME)_$(CONFIG_PROJECT_NAME_SUFFIX)
endif

ifeq ($(FULL_PROJECT_NAME),$(FULL_CURR_PROJECT_NAME))
    $(info !--- name is not unique)
    $(error )
endif
