
include $(MAKEFILE_DEFS_ROOT_DIR)/common.mk

# creating "project_config.h file" :
ifeq ($(findstring WINDOWS,$(COMPILER_HOST_OS)),WINDOWS) 
    $(shell echo /*file is auto generated by running 'make menuconfig' */ > $(PROJECT_CONFIG_H_FILE))
    CONFIG_CONTENT := $(shell findstr /b /c:"CONFIG" .config)
    CONFIG_CONTENT := $(patsubst %,echo \#define % >> $(PROJECT_CONFIG_H_FILE) & ,$(CONFIG_CONTENT))
else ifeq ($(findstring LINUX,$(COMPILER_HOST_OS)),LINUX) 
    $(shell echo /*file is auto generated by running 'make menuconfig'\*/  > $(PROJECT_CONFIG_H_FILE))
    CONFIG_CONTENT := $(shell cat .config | grep '^CONFIG')
    CONFIG_CONTENT := $(subst ",\",$(CONFIG_CONTENT))
    CONFIG_CONTENT := $(patsubst %,echo "\#define %" >> $(PROJECT_CONFIG_H_FILE) ; ,$(CONFIG_CONTENT))
endif

EQUAL_SIGN := =
CONFIG_CONTENT := $(subst $(EQUAL_SIGN)y,$(SPACE)  $(SPACE)1,$(CONFIG_CONTENT))
CONFIG_CONTENT := $(subst $(EQUAL_SIGN),$(SPACE)  $(SPACE),$(CONFIG_CONTENT))
DUMMY:=$(shell $(CONFIG_CONTENT))


all :
	$(info auto generated project_config.h created)
